//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.5
//
// <auto-generated>
//
// Generated from file `Tester.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Tester;

public interface TesterIfacePrx extends com.zeroc.Ice.ObjectPrx
{
    default void processSmall(SmallData smallData)
    {
        processSmall(smallData, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void processSmall(SmallData smallData, java.util.Map<String, String> context)
    {
        _iceI_processSmallAsync(smallData, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> processSmallAsync(SmallData smallData)
    {
        return _iceI_processSmallAsync(smallData, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> processSmallAsync(SmallData smallData, java.util.Map<String, String> context)
    {
        return _iceI_processSmallAsync(smallData, context, false);
    }

    /**
     * @hidden
     * @param iceP_smallData -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_processSmallAsync(SmallData iceP_smallData, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "processSmall", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     SmallData.ice_write(ostr, iceP_smallData);
                 }, null);
        return f;
    }

    default void processMedium(MediumData mediumData)
    {
        processMedium(mediumData, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void processMedium(MediumData mediumData, java.util.Map<String, String> context)
    {
        _iceI_processMediumAsync(mediumData, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> processMediumAsync(MediumData mediumData)
    {
        return _iceI_processMediumAsync(mediumData, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> processMediumAsync(MediumData mediumData, java.util.Map<String, String> context)
    {
        return _iceI_processMediumAsync(mediumData, context, false);
    }

    /**
     * @hidden
     * @param iceP_mediumData -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_processMediumAsync(MediumData iceP_mediumData, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "processMedium", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     MediumData.ice_write(ostr, iceP_mediumData);
                 }, null);
        return f;
    }

    default void processBig(BigData bigData)
    {
        processBig(bigData, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void processBig(BigData bigData, java.util.Map<String, String> context)
    {
        _iceI_processBigAsync(bigData, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> processBigAsync(BigData bigData)
    {
        return _iceI_processBigAsync(bigData, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> processBigAsync(BigData bigData, java.util.Map<String, String> context)
    {
        return _iceI_processBigAsync(bigData, context, false);
    }

    /**
     * @hidden
     * @param iceP_bigData -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_processBigAsync(BigData iceP_bigData, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "processBig", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     BigData.ice_write(ostr, iceP_bigData);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static TesterIfacePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), TesterIfacePrx.class, _TesterIfacePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static TesterIfacePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), TesterIfacePrx.class, _TesterIfacePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static TesterIfacePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), TesterIfacePrx.class, _TesterIfacePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static TesterIfacePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), TesterIfacePrx.class, _TesterIfacePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static TesterIfacePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, TesterIfacePrx.class, _TesterIfacePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static TesterIfacePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, TesterIfacePrx.class, _TesterIfacePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default TesterIfacePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (TesterIfacePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default TesterIfacePrx ice_adapterId(String newAdapterId)
    {
        return (TesterIfacePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default TesterIfacePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (TesterIfacePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default TesterIfacePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (TesterIfacePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default TesterIfacePrx ice_invocationTimeout(int newTimeout)
    {
        return (TesterIfacePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default TesterIfacePrx ice_connectionCached(boolean newCache)
    {
        return (TesterIfacePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default TesterIfacePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (TesterIfacePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default TesterIfacePrx ice_secure(boolean b)
    {
        return (TesterIfacePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default TesterIfacePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (TesterIfacePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default TesterIfacePrx ice_preferSecure(boolean b)
    {
        return (TesterIfacePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default TesterIfacePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (TesterIfacePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default TesterIfacePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (TesterIfacePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default TesterIfacePrx ice_collocationOptimized(boolean b)
    {
        return (TesterIfacePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default TesterIfacePrx ice_twoway()
    {
        return (TesterIfacePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default TesterIfacePrx ice_oneway()
    {
        return (TesterIfacePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default TesterIfacePrx ice_batchOneway()
    {
        return (TesterIfacePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default TesterIfacePrx ice_datagram()
    {
        return (TesterIfacePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default TesterIfacePrx ice_batchDatagram()
    {
        return (TesterIfacePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default TesterIfacePrx ice_compress(boolean co)
    {
        return (TesterIfacePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default TesterIfacePrx ice_timeout(int t)
    {
        return (TesterIfacePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default TesterIfacePrx ice_connectionId(String connectionId)
    {
        return (TesterIfacePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default TesterIfacePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (TesterIfacePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::Tester::TesterIface";
    }
}
