# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Office.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Office.proto',
  package='office',
  syntax='proto3',
  serialized_options=b'\n\005protoB\013OfficeProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cOffice.proto\x12\x06office\"9\n\x06\x43lient\x12\x10\n\x08\x63lientID\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07surname\x18\x03 \x01(\t\"\x12\n\x04\x43\x61se\x12\n\n\x02id\x18\x01 \x01(\r\"=\n\x07\x43\x61seAck\x12\x1a\n\x04\x63\x61se\x18\x01 \x01(\x0b\x32\x0c.office.Case\x12\x16\n\x0eresolutionTime\x18\x02 \x01(\r\"9\n\nCaseResult\x12\x1a\n\x04\x63\x61se\x18\x01 \x01(\x0b\x32\x0c.office.Case\x12\x0f\n\x07message\x18\x02 \x01(\t\"l\n\x12RegisterCaseResult\x12\"\n\x07\x63\x61seAck\x18\x01 \x01(\x0b\x32\x0f.office.CaseAckH\x00\x12(\n\ncaseResult\x18\x02 \x01(\x0b\x32\x12.office.CaseResultH\x00\x42\x08\n\x06result\"E\n\x11\x44riverLicenseData\x12\x1e\n\x06\x63lient\x18\x01 \x01(\x0b\x32\x0e.office.Client\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\",\n\nIDCardData\x12\x1e\n\x06\x63lient\x18\x01 \x01(\x0b\x32\x0e.office.Client\"b\n\x13RegisterCompanyData\x12\x1e\n\x06\x63lient\x18\x01 \x01(\x0b\x32\x0e.office.Client\x12\x13\n\x0b\x63ompanyName\x18\x02 \x01(\t\x12\x16\n\x0estartUpCapital\x18\x03 \x01(\x01\"-\n\x0b\x43lientReady\x12\x1e\n\x06\x63lient\x18\x01 \x01(\x0b\x32\x0e.office.Client\"\xe3\x01\n\x0f\x43\x61seRequestData\x12*\n\x0b\x63lientReady\x18\x01 \x01(\x0b\x32\x13.office.ClientReadyH\x00\x12\x36\n\x11\x64riverLicenseData\x18\x02 \x01(\x0b\x32\x19.office.DriverLicenseDataH\x00\x12(\n\nidCardData\x18\x03 \x01(\x0b\x32\x12.office.IDCardDataH\x00\x12:\n\x13registerCompanyData\x18\x04 \x01(\x0b\x32\x1b.office.RegisterCompanyDataH\x00\x42\x06\n\x04Type\"9\n\x12\x43\x61seResultSequence\x12#\n\x07results\x18\x01 \x03(\x0b\x32\x12.office.CaseResult2\x8c\x01\n\x06Office\x12\x46\n\x0b\x63\x61seRequest\x12\x17.office.CaseRequestData\x1a\x1a.office.RegisterCaseResult(\x01\x30\x01\x12:\n\x0chelloRequest\x12\x0e.office.Client\x1a\x1a.office.CaseResultSequenceB\x14\n\x05protoB\x0bOfficeProtob\x06proto3'
)




_CLIENT = _descriptor.Descriptor(
  name='Client',
  full_name='office.Client',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientID', full_name='office.Client.clientID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='office.Client.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='surname', full_name='office.Client.surname', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=81,
)


_CASE = _descriptor.Descriptor(
  name='Case',
  full_name='office.Case',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='office.Case.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=101,
)


_CASEACK = _descriptor.Descriptor(
  name='CaseAck',
  full_name='office.CaseAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='case', full_name='office.CaseAck.case', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resolutionTime', full_name='office.CaseAck.resolutionTime', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=164,
)


_CASERESULT = _descriptor.Descriptor(
  name='CaseResult',
  full_name='office.CaseResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='case', full_name='office.CaseResult.case', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='office.CaseResult.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=223,
)


_REGISTERCASERESULT = _descriptor.Descriptor(
  name='RegisterCaseResult',
  full_name='office.RegisterCaseResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='caseAck', full_name='office.RegisterCaseResult.caseAck', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='caseResult', full_name='office.RegisterCaseResult.caseResult', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='result', full_name='office.RegisterCaseResult.result',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=225,
  serialized_end=333,
)


_DRIVERLICENSEDATA = _descriptor.Descriptor(
  name='DriverLicenseData',
  full_name='office.DriverLicenseData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client', full_name='office.DriverLicenseData.client', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='category', full_name='office.DriverLicenseData.category', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=404,
)


_IDCARDDATA = _descriptor.Descriptor(
  name='IDCardData',
  full_name='office.IDCardData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client', full_name='office.IDCardData.client', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=450,
)


_REGISTERCOMPANYDATA = _descriptor.Descriptor(
  name='RegisterCompanyData',
  full_name='office.RegisterCompanyData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client', full_name='office.RegisterCompanyData.client', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='companyName', full_name='office.RegisterCompanyData.companyName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='startUpCapital', full_name='office.RegisterCompanyData.startUpCapital', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=452,
  serialized_end=550,
)


_CLIENTREADY = _descriptor.Descriptor(
  name='ClientReady',
  full_name='office.ClientReady',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client', full_name='office.ClientReady.client', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=552,
  serialized_end=597,
)


_CASEREQUESTDATA = _descriptor.Descriptor(
  name='CaseRequestData',
  full_name='office.CaseRequestData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientReady', full_name='office.CaseRequestData.clientReady', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='driverLicenseData', full_name='office.CaseRequestData.driverLicenseData', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='idCardData', full_name='office.CaseRequestData.idCardData', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='registerCompanyData', full_name='office.CaseRequestData.registerCompanyData', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Type', full_name='office.CaseRequestData.Type',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=600,
  serialized_end=827,
)


_CASERESULTSEQUENCE = _descriptor.Descriptor(
  name='CaseResultSequence',
  full_name='office.CaseResultSequence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='office.CaseResultSequence.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=829,
  serialized_end=886,
)

_CASEACK.fields_by_name['case'].message_type = _CASE
_CASERESULT.fields_by_name['case'].message_type = _CASE
_REGISTERCASERESULT.fields_by_name['caseAck'].message_type = _CASEACK
_REGISTERCASERESULT.fields_by_name['caseResult'].message_type = _CASERESULT
_REGISTERCASERESULT.oneofs_by_name['result'].fields.append(
  _REGISTERCASERESULT.fields_by_name['caseAck'])
_REGISTERCASERESULT.fields_by_name['caseAck'].containing_oneof = _REGISTERCASERESULT.oneofs_by_name['result']
_REGISTERCASERESULT.oneofs_by_name['result'].fields.append(
  _REGISTERCASERESULT.fields_by_name['caseResult'])
_REGISTERCASERESULT.fields_by_name['caseResult'].containing_oneof = _REGISTERCASERESULT.oneofs_by_name['result']
_DRIVERLICENSEDATA.fields_by_name['client'].message_type = _CLIENT
_IDCARDDATA.fields_by_name['client'].message_type = _CLIENT
_REGISTERCOMPANYDATA.fields_by_name['client'].message_type = _CLIENT
_CLIENTREADY.fields_by_name['client'].message_type = _CLIENT
_CASEREQUESTDATA.fields_by_name['clientReady'].message_type = _CLIENTREADY
_CASEREQUESTDATA.fields_by_name['driverLicenseData'].message_type = _DRIVERLICENSEDATA
_CASEREQUESTDATA.fields_by_name['idCardData'].message_type = _IDCARDDATA
_CASEREQUESTDATA.fields_by_name['registerCompanyData'].message_type = _REGISTERCOMPANYDATA
_CASEREQUESTDATA.oneofs_by_name['Type'].fields.append(
  _CASEREQUESTDATA.fields_by_name['clientReady'])
_CASEREQUESTDATA.fields_by_name['clientReady'].containing_oneof = _CASEREQUESTDATA.oneofs_by_name['Type']
_CASEREQUESTDATA.oneofs_by_name['Type'].fields.append(
  _CASEREQUESTDATA.fields_by_name['driverLicenseData'])
_CASEREQUESTDATA.fields_by_name['driverLicenseData'].containing_oneof = _CASEREQUESTDATA.oneofs_by_name['Type']
_CASEREQUESTDATA.oneofs_by_name['Type'].fields.append(
  _CASEREQUESTDATA.fields_by_name['idCardData'])
_CASEREQUESTDATA.fields_by_name['idCardData'].containing_oneof = _CASEREQUESTDATA.oneofs_by_name['Type']
_CASEREQUESTDATA.oneofs_by_name['Type'].fields.append(
  _CASEREQUESTDATA.fields_by_name['registerCompanyData'])
_CASEREQUESTDATA.fields_by_name['registerCompanyData'].containing_oneof = _CASEREQUESTDATA.oneofs_by_name['Type']
_CASERESULTSEQUENCE.fields_by_name['results'].message_type = _CASERESULT
DESCRIPTOR.message_types_by_name['Client'] = _CLIENT
DESCRIPTOR.message_types_by_name['Case'] = _CASE
DESCRIPTOR.message_types_by_name['CaseAck'] = _CASEACK
DESCRIPTOR.message_types_by_name['CaseResult'] = _CASERESULT
DESCRIPTOR.message_types_by_name['RegisterCaseResult'] = _REGISTERCASERESULT
DESCRIPTOR.message_types_by_name['DriverLicenseData'] = _DRIVERLICENSEDATA
DESCRIPTOR.message_types_by_name['IDCardData'] = _IDCARDDATA
DESCRIPTOR.message_types_by_name['RegisterCompanyData'] = _REGISTERCOMPANYDATA
DESCRIPTOR.message_types_by_name['ClientReady'] = _CLIENTREADY
DESCRIPTOR.message_types_by_name['CaseRequestData'] = _CASEREQUESTDATA
DESCRIPTOR.message_types_by_name['CaseResultSequence'] = _CASERESULTSEQUENCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Client = _reflection.GeneratedProtocolMessageType('Client', (_message.Message,), {
  'DESCRIPTOR' : _CLIENT,
  '__module__' : 'Office_pb2'
  # @@protoc_insertion_point(class_scope:office.Client)
  })
_sym_db.RegisterMessage(Client)

Case = _reflection.GeneratedProtocolMessageType('Case', (_message.Message,), {
  'DESCRIPTOR' : _CASE,
  '__module__' : 'Office_pb2'
  # @@protoc_insertion_point(class_scope:office.Case)
  })
_sym_db.RegisterMessage(Case)

CaseAck = _reflection.GeneratedProtocolMessageType('CaseAck', (_message.Message,), {
  'DESCRIPTOR' : _CASEACK,
  '__module__' : 'Office_pb2'
  # @@protoc_insertion_point(class_scope:office.CaseAck)
  })
_sym_db.RegisterMessage(CaseAck)

CaseResult = _reflection.GeneratedProtocolMessageType('CaseResult', (_message.Message,), {
  'DESCRIPTOR' : _CASERESULT,
  '__module__' : 'Office_pb2'
  # @@protoc_insertion_point(class_scope:office.CaseResult)
  })
_sym_db.RegisterMessage(CaseResult)

RegisterCaseResult = _reflection.GeneratedProtocolMessageType('RegisterCaseResult', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERCASERESULT,
  '__module__' : 'Office_pb2'
  # @@protoc_insertion_point(class_scope:office.RegisterCaseResult)
  })
_sym_db.RegisterMessage(RegisterCaseResult)

DriverLicenseData = _reflection.GeneratedProtocolMessageType('DriverLicenseData', (_message.Message,), {
  'DESCRIPTOR' : _DRIVERLICENSEDATA,
  '__module__' : 'Office_pb2'
  # @@protoc_insertion_point(class_scope:office.DriverLicenseData)
  })
_sym_db.RegisterMessage(DriverLicenseData)

IDCardData = _reflection.GeneratedProtocolMessageType('IDCardData', (_message.Message,), {
  'DESCRIPTOR' : _IDCARDDATA,
  '__module__' : 'Office_pb2'
  # @@protoc_insertion_point(class_scope:office.IDCardData)
  })
_sym_db.RegisterMessage(IDCardData)

RegisterCompanyData = _reflection.GeneratedProtocolMessageType('RegisterCompanyData', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERCOMPANYDATA,
  '__module__' : 'Office_pb2'
  # @@protoc_insertion_point(class_scope:office.RegisterCompanyData)
  })
_sym_db.RegisterMessage(RegisterCompanyData)

ClientReady = _reflection.GeneratedProtocolMessageType('ClientReady', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTREADY,
  '__module__' : 'Office_pb2'
  # @@protoc_insertion_point(class_scope:office.ClientReady)
  })
_sym_db.RegisterMessage(ClientReady)

CaseRequestData = _reflection.GeneratedProtocolMessageType('CaseRequestData', (_message.Message,), {
  'DESCRIPTOR' : _CASEREQUESTDATA,
  '__module__' : 'Office_pb2'
  # @@protoc_insertion_point(class_scope:office.CaseRequestData)
  })
_sym_db.RegisterMessage(CaseRequestData)

CaseResultSequence = _reflection.GeneratedProtocolMessageType('CaseResultSequence', (_message.Message,), {
  'DESCRIPTOR' : _CASERESULTSEQUENCE,
  '__module__' : 'Office_pb2'
  # @@protoc_insertion_point(class_scope:office.CaseResultSequence)
  })
_sym_db.RegisterMessage(CaseResultSequence)


DESCRIPTOR._options = None

_OFFICE = _descriptor.ServiceDescriptor(
  name='Office',
  full_name='office.Office',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=889,
  serialized_end=1029,
  methods=[
  _descriptor.MethodDescriptor(
    name='caseRequest',
    full_name='office.Office.caseRequest',
    index=0,
    containing_service=None,
    input_type=_CASEREQUESTDATA,
    output_type=_REGISTERCASERESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='helloRequest',
    full_name='office.Office.helloRequest',
    index=1,
    containing_service=None,
    input_type=_CLIENT,
    output_type=_CASERESULTSEQUENCE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OFFICE)

DESCRIPTOR.services_by_name['Office'] = _OFFICE

# @@protoc_insertion_point(module_scope)
