# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Office_pb2 as Office__pb2


class OfficeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.caseRequest = channel.stream_stream(
                '/office.Office/caseRequest',
                request_serializer=Office__pb2.CaseRequestData.SerializeToString,
                response_deserializer=Office__pb2.RegisterCaseResult.FromString,
                )
        self.helloRequest = channel.unary_unary(
                '/office.Office/helloRequest',
                request_serializer=Office__pb2.Client.SerializeToString,
                response_deserializer=Office__pb2.CaseResultSequence.FromString,
                )


class OfficeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def caseRequest(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def helloRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OfficeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'caseRequest': grpc.stream_stream_rpc_method_handler(
                    servicer.caseRequest,
                    request_deserializer=Office__pb2.CaseRequestData.FromString,
                    response_serializer=Office__pb2.RegisterCaseResult.SerializeToString,
            ),
            'helloRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.helloRequest,
                    request_deserializer=Office__pb2.Client.FromString,
                    response_serializer=Office__pb2.CaseResultSequence.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'office.Office', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Office(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def caseRequest(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/office.Office/caseRequest',
            Office__pb2.CaseRequestData.SerializeToString,
            Office__pb2.RegisterCaseResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def helloRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/office.Office/helloRequest',
            Office__pb2.Client.SerializeToString,
            Office__pb2.CaseResultSequence.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
