# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Tester_pb2 as Tester__pb2


class TesterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.processSmall = channel.unary_unary(
                '/tester.Tester/processSmall',
                request_serializer=Tester__pb2.SmallData.SerializeToString,
                response_deserializer=Tester__pb2.Empty.FromString,
                )
        self.processMedium = channel.unary_unary(
                '/tester.Tester/processMedium',
                request_serializer=Tester__pb2.MediumData.SerializeToString,
                response_deserializer=Tester__pb2.Empty.FromString,
                )
        self.processBig = channel.unary_unary(
                '/tester.Tester/processBig',
                request_serializer=Tester__pb2.BigData.SerializeToString,
                response_deserializer=Tester__pb2.Empty.FromString,
                )


class TesterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def processSmall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def processMedium(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def processBig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TesterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'processSmall': grpc.unary_unary_rpc_method_handler(
                    servicer.processSmall,
                    request_deserializer=Tester__pb2.SmallData.FromString,
                    response_serializer=Tester__pb2.Empty.SerializeToString,
            ),
            'processMedium': grpc.unary_unary_rpc_method_handler(
                    servicer.processMedium,
                    request_deserializer=Tester__pb2.MediumData.FromString,
                    response_serializer=Tester__pb2.Empty.SerializeToString,
            ),
            'processBig': grpc.unary_unary_rpc_method_handler(
                    servicer.processBig,
                    request_deserializer=Tester__pb2.BigData.FromString,
                    response_serializer=Tester__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tester.Tester', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Tester(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def processSmall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tester.Tester/processSmall',
            Tester__pb2.SmallData.SerializeToString,
            Tester__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def processMedium(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tester.Tester/processMedium',
            Tester__pb2.MediumData.SerializeToString,
            Tester__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def processBig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tester.Tester/processBig',
            Tester__pb2.BigData.SerializeToString,
            Tester__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
